### ISSUE TITLE
SystemVerilog Assertion and fork join Support

### ISSUE THREAD

**Issue by shaishavmehta** [fvutils/pyvsc#10]
Hi Matthew,

I am new to **pyvsc** and curious to know that are you going to provide support for **SystemVerilog** **assertions** and **fork-join,join_any, join_none** statements in the future? 

Thanks for your contributions until now.

**Comment by mballance** [comment]
Hi,
    SystemVerilog has many features in a single language -- for RTL design, object-oriented verification, assertions, etc. The approach to supporting verification like these in Python has been to have several libraries that each support a subset. PyVSC supports constraints, random data, and coverage. [cocotb](https://docs.cocotb.org/en/stable/) provides features for interfacing with simulation at the signal level, and also provides features like the fork/join. I'm not aware of a specific Python library that aims to support assertions.
    So, the short answer is that PyVSC does not plan to support SVA-style assertions or fork/join. I'd be interested to understand your use model, and the reasons that existing libraries like cocotb do not meet your needs.

Thanks and Best Regards,
Matthew
