### ISSUE TITLE
Incorrect covergroup percentage 

### ISSUE THREAD

**Issue by shrujal20** [fvutils/pyvsc#101]
Hi @mballance ,
I am trying one example related to coverage, but it seems that sometimes it is showing incorrect covergroup percentage. following is the code:
```
import vsc
from vsc import *

@vsc.randobj
class parent(object):
    def __init__(self):
        self.a = vsc.rand_bit_t(2)
        #self.b = vsc.rand_bit_t(8)

@vsc.covergroup
class my_covergroup(object):

    def __init__(self):
        self.with_sample(dict(it=parent()))
        self.cp1 = vsc.coverpoint(self.it.a, bins=dict(
            a_bin = bin(1,2,3)))
        self.c = vsc.coverpoint(self.it.a, bins=dict(
            a_bin1 = bin_array([], [0,3])))
        self.cp2 = vsc.coverpoint(self.it.a, bins=dict(
            b_bin = bin(2,3)))

pr = parent()
cover = my_covergroup()
for i in range(5):
    pr.randomize()
    print("a = ", pr.a)
    cover.sample(pr)
print("coverage: ", cover.get_coverage())
```
For this it is giving an output like following:
![image](https://user-images.githubusercontent.com/84434636/126756250-e2dfdf0c-cc4f-4c69-a390-f7cb40820691.png)

As we can see here, coverage percentage of cp2 is showing 100% but here it is covering only one value(that is 3). So it should give coverage percentage of cp2 = 50%.
Can you please take a look into this ?

**Comment by mballance** [comment]
Hi @shrujal20,
    If I'm reading this correctly:
- cp1 is a single bin monitoring values [1,2,3]
- c is an array of bins monitoring values [0, 1, 2, 3]
- cp2 is a single bin monitoring values [2,3]

Looking at c, it appears randomization produced a==3 four times and a==1 one time.

Based on that, it looks to me like having four hits in the single-bin [2,3] is correct.

Please let me know if I'm overlooking something.

Best Regards,
Matthew

**Comment by shrujal20** [comment]
Hi @mballance,

I was calculating in a different way.
Thanks for the explanation.
