### ISSUE TITLE
solve_order() example hitting exception

### ISSUE THREAD

**Issue by qzcx** [fvutils/pyvsc#103]
In attempting to influence the order of randomization, I tried to use the solve_order() constraint. I hit the following exception when I tried the example [here](https://pyvsc.readthedocs.io/en/latest/constraints.html#solve-order). How should this example be changed to avoid this exception?

> Exception while processing constraint: solve_before can only be used at a constraint top level

```
import vsc 
@vsc.randobj
class my_c(object):

    def __init__(self):
        self.a = vsc.rand_bit_t()
        self.b = vsc.rand_uint8_t()

    @vsc.constraint
    def ab_c(self):
        vsc.solve_order(self.a, self.b)

        with vsc.if_then(self.a == 0):
            self.b == 4
        with vsc.else_then:
            self.b != 4

c = my_c()
c.randomize()
print(f"a {c.a} b {c.b}")
```

Thanks,
qzcx

**Comment by mballance** [comment]
Hmm... This is puzzling. I'm unable to reproduce the exception using your testcase. The exception you mention is intended to trigger when the solve-order constraint is placed inside a conditional. For example:
https://github.com/fvutils/pyvsc/blob/28907013da1472fc5f45d8716aa112b8df00b673/ve/unit/test_constraint_solve_order.py#L35-L56

Are you running just the code above, or is it in a larger context?

**Comment by qzcx** [comment]
I went back to my code from this weekend and can't reproduce the error. I'll keep looking at it and see what I might have changed. I'll close this and re-open if I can figure out what I was doing before.

Thanks for looking.
