### ISSUE TITLE
Coverpoints incorrectly assign all samples to a single bin

### ISSUE THREAD

**Issue by msmftc** [fvutils/pyvsc#108]
In the test program shown below, the properties "type" and "disp" are random and well-distributed across their ranges.  "type" can be 0 or 1, and "disp" can range [0, 4096].  However, coverpoints for these properties report that "type" is always 0 and that "disp" is always [0, 1024].  This is incorrect.  My PyVSC version is pyvsc-0.5.5.20210822.1

`import vsc

@vsc.randobj
class BranchInstr:
    def __init__(self):
        self.type = vsc.rand_bit_t(1)
        self.disp = vsc.rand_bit_t(19)

    @vsc.constraint
    def short_offset_cnstr(self):
        self.disp <= 4096

    def __str__(self):
        return(f"type = {self.type}, displacement = {self.disp}")

@vsc.covergroup
class BranchInstr_cg:
    def __init__(self):
        self.with_sample(
            item = BranchInstr()
        )

        self.type = vsc.coverpoint(self.item.type)

        self.disp_cp = vsc.coverpoint(self.item.disp, bins = {
            "small_pos" : vsc.bin_array([4], [0, 4096])
        })

branchInstr = BranchInstr()
branchInstr_cg = BranchInstr_cg()

for i in range(32):
    branchInstr.randomize()
    branchInstr_cg.sample(branchInstr)
    print(branchInstr)

vsc.report_coverage(details=True)`

type = 0, displacement = 483
type = 1, displacement = 1687
type = 0, displacement = 2790
type = 0, displacement = 3042
type = 0, displacement = 3980
type = 1, displacement = 2925
type = 1, displacement = 3014
type = 0, displacement = 3116
type = 1, displacement = 1175
type = 1, displacement = 343
type = 1, displacement = 2876
type = 0, displacement = 3972
type = 0, displacement = 1658
type = 0, displacement = 3087
type = 1, displacement = 3933
type = 0, displacement = 1394
type = 1, displacement = 2294
type = 0, displacement = 448
type = 1, displacement = 3174
type = 1, displacement = 3618
type = 0, displacement = 69
type = 0, displacement = 3572
type = 1, displacement = 2402
type = 0, displacement = 1257
type = 0, displacement = 617
type = 1, displacement = 1021
type = 1, displacement = 282
type = 1, displacement = 3212
type = 1, displacement = 1121
type = 0, displacement = 529
type = 1, displacement = 3753
type = 1, displacement = 2754
TYPE BranchInstr_cg : 62.500000%
    CVP type : 100.000000%
    Bins:
        type[0] : 32
    CVP disp_cp : 25.000000%
    Bins:
        small_pos[0] : 32
        small_pos[1] : 0
        small_pos[2] : 0
        small_pos[3] : 0
    INST BranchInstr_cg : 62.500000%
        CVP type : 100.000000%
        Bins:
            type[0] : 32
        CVP disp_cp : 25.000000%
        Bins:
            small_pos[0] : 32
            small_pos[1] : 0
            small_pos[2] : 0
            small_pos[3] : 0

**Comment by msmftc** [comment]
Some of my program's indentation was lost during copy-and-paste.  The program is simple enough that you can infer the original indentation.

**Comment by msmftc** [comment]
Thank-you Matthew.  I verified that calling with_sample with 'dict(item = BranchInstr())' does fix some of the binning.

As you noted, there is bug in auto-binning of unsigned integers.  Auto-binning of enumerations is correct.  Example code and output shown below.

```Python
import vsc
import enum

class Name(enum.Enum):
    A = enum.auto()
    B = enum.auto()
    C = enum.auto()

@vsc.randobj
class BranchInstr:
    def __init__(self):
        self.type = vsc.rand_bit_t(1)
        self.disp = vsc.rand_bit_t(19)
        self.name = vsc.rand_enum_t(Name)

    @vsc.constraint
    def short_offset_cnstr(self):
        self.disp <= 4096

    def __str__(self):
        return(f"type = {self.type}, name = {self.name} displacement = {self.disp}")


@vsc.covergroup
class BranchInstr_cg:
    def __init__(self):
        self.with_sample(
            dict(item = BranchInstr())
        )

        # Auto-binned coverpoint of bit field shows a bug.
        self.type = vsc.coverpoint(self.item.type)

        # Explicitly binned coverpoint of bit field is accurate.
        self.binned_type = vsc.coverpoint(self.item.type, bins = {
            "zero" : vsc.bin(0),
            "one" : vsc.bin(1)
        })

        # Auto-binned coverpoint of enumeration is accurate.
        self.name = vsc.coverpoint(self.item.name)

        # Explicitly binned ranges of unsigned integer are accurate.
        self.disp_cp = vsc.coverpoint(self.item.disp, bins = {
            "small_pos" : vsc.bin_array([4], [0, 4096])
        })


branchInstr = BranchInstr()
branchInstr_cg = BranchInstr_cg()

for i in range(32):
    branchInstr.randomize()
    branchInstr_cg.sample(branchInstr)
    print(branchInstr)

vsc.report_coverage(details=True)
```

type = 1, name = Name.A displacement = 2727
type = 0, name = Name.C displacement = 2703
type = 0, name = Name.B displacement = 3369
type = 1, name = Name.B displacement = 1530
type = 0, name = Name.C displacement = 2085
type = 0, name = Name.B displacement = 1104
type = 1, name = Name.C displacement = 2903
type = 1, name = Name.C displacement = 774
type = 1, name = Name.B displacement = 614
type = 0, name = Name.B displacement = 3387
type = 0, name = Name.C displacement = 1515
type = 1, name = Name.B displacement = 187
type = 1, name = Name.A displacement = 3249
type = 0, name = Name.A displacement = 3877
type = 0, name = Name.C displacement = 959
type = 1, name = Name.C displacement = 2595
type = 0, name = Name.C displacement = 3090
type = 1, name = Name.C displacement = 1459
type = 0, name = Name.A displacement = 3198
type = 0, name = Name.C displacement = 3110
type = 0, name = Name.A displacement = 1311
type = 1, name = Name.B displacement = 4008
type = 1, name = Name.A displacement = 3457
type = 1, name = Name.C displacement = 3485
type = 1, name = Name.B displacement = 2412
type = 0, name = Name.A displacement = 618
type = 1, name = Name.A displacement = 1399
type = 1, name = Name.B displacement = 3676
type = 1, name = Name.A displacement = 2941
type = 0, name = Name.A displacement = 928
type = 0, name = Name.C displacement = 1998
type = 0, name = Name.B displacement = 97
TYPE <vsc.coverage.coverpoint object at 0x7ff5ba32fd68> : 100.000000%
    CVP type : 100.000000%
    Bins:
        type[0] : 32
    CVP binned_type : 100.000000%
    Bins:
        zero : 16
        one : 16
    CVP name : 100.000000%
    Bins:
        Name.A : 10
        Name.B : 10
        Name.C : 12
    CVP disp_cp : 100.000000%
    Bins:
        small_pos[0] : 7
        small_pos[1] : 7
        small_pos[2] : 7
        small_pos[3] : 11
    INST <vsc.coverage.coverpoint object at 0x7ff5ba32fd68> : 100.000000%
        CVP type : 100.000000%
        Bins:
            type[0] : 32
        CVP binned_type : 100.000000%
        Bins:
            zero : 16
            one : 16
        CVP name : 100.000000%
        Bins:
            Name.A : 10
            Name.B : 10
            Name.C : 12
        CVP disp_cp : 100.000000%
        Bins:
            small_pos[0] : 7
            small_pos[1] : 7
            small_pos[2] : 7
            small_pos[3] : 11

**Comment by mballance** [comment]
Hi Michael,
    I've resolved this issue and the single-bit bin issue in the 0.5.7 release, which should now be available on PyPi.

Best Regards,
Matthew
