### ISSUE TITLE
Pip installation dependency pyboolector fails

### ISSUE THREAD

**Issue by ben-marshall** [fvutils/pyvsc#109]
Hi there

I think I've hit a similar issue to #54 . When I try to install pyvsc, I get:

```
$ python3 --version
Python 3.6.8
$ pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
$ sudo pip3 install pyvsc
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting pyvsc
  Using cached https://files.pythonhosted.org/packages/20/68/a708955a9baff9afd2e8eb138df163a77849f729f01a1b5f9edd16c2a018/pyvsc-0.5.7.20210909.1-py2.py3-none-any.whl
Collecting toposort (from pyvsc)
  Using cached https://files.pythonhosted.org/packages/f2/7d/55784e894ee0cde2474fb977ffd1651e74e840a9f92e1d847f7e3115d5ec/toposort-1.6-py2.py3-none-any.whl
Collecting pyboolector>=3.2.2 (from pyvsc)
  Using cached https://files.pythonhosted.org/packages/9d/d2/4b244e2d3100b1d7af0e68b0181538d33d4a84e75305e296080eb74f26f2/PyBoolector-3.2.2.20210617.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wi1vpk9x/pyboolector/setup.py", line 14, in <module>
        with open(cmakelists_txt, "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-wi1vpk9x/CMakeLists.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wi1vpk9x/pyboolector/
```

I'm running CentOS 7.

I'm sorry this does seem so similar to #54, but I don't know enough about python packaging to fix it myself.

Thanks,
Ben

**Comment by mballance** [comment]
Hi Ben,
    The other thing that can trigger this issue is having an older version of 'pip' installed. Given that you're running CentOS 7, this is certainly a possibility. 
    PyBoolector needs to be installed from a binary package. Unfortunately, pip falls back to trying to install from source if it doesn't recognize the binary package...

    Please try the following:

```
% python3 -m pip install --upgrade pip
% python3 -m pip install pyboolector
```

There are some other `pip install` flags that you can try if pip still seems to be looking at the cached source version of the package. Hope this helps!

-Matthew

**Comment by ben-marshall** [comment]
Hi Matthew

That solved it! I had an embarrassingly out of date pip. Running the two commands you suggested solved everything. Thanks a lot for the speedy response.

Cheers,
Ben
