### ISSUE TITLE
Error when creating randomized register consisting of randomized bits

### ISSUE THREAD

**Issue by pmassolino** [fvutils/pyvsc#110]
Hello,

I was trying to use pyvsc to randomize the full content of a register, while randomizing each bit separately. The idea is to  easily fully randomize the contents of a register and be able to constraint the value of each bit. In the example below I tried to randomize  a 4-bit register with bits 3 and 2 being 1 and 0, respectively, and the other bits being random. When I executed the code below:

```
import vsc

@vsc.randobj
class my_d:

    def __init__(self):
        self.value = vsc.rand_bit_t(4)
        self.a = vsc.rand_bit_t(1)
        self.b = vsc.rand_bit_t(1)

    @vsc.constraint
    def a_c1(self):
        vsc.solve_order(self.a, self.value)
        vsc.solve_order(self.b, self.value)

    @vsc.constraint
    def a_c2(self):
        self.value[3] == self.a
        self.value[2] == self.b

td = my_d()
for i in range(0,1):
    with td.randomize_with() as it:
        it.a == 1
        it.b == 0

    print("a = " + str(td.a) + "  b = " + str(td.b) + "  value = " + str(hex(td.value)))
```

 I got the following output:

```
Note: variable bounds model failed to converge in 100 iterations
Note: variable bounds model failed to converge in 100 iterations
a = 1  b = 0  value = 0xb
```

And If I perform the tests more than once, then "value" is always the same (0xb), but it should be different since bits 0 and 1 are not constrained. I am using `pyvsc                         0.5.7.20210909.1  `  

Any ideas on what is the problem? Is it expected/allowed to have one randomized value inside another?

**Comment by mballance** [comment]
Hi @pmassolino,

First off, the case shown above is absolutely intended to work. There are no restrictions on bit-slice constraints and/or relating variables as you've done. The 'variable bounds model failed to converge' is actually a good clue -- at least from an implementation perspective. PyVSC adds randomization-biasing constraints to produce random results with a reasonable distribution. It performs some pre-analysis on the constraint expressions to establish domains that have a high probability of being reachable. This helps to deal with common cases where, for example, the user has captured a 32-bit random variable and constrained it to be [1,2,4,8]. Without some domain analysis, the vast majority of our attempts to select a random value for the variable will be unsuccessful.

The 'failed to converge' message occurs when that domain-analysis process fails. As you have observed, correct results are still produced ('b1011 matches the constraints), but the results are not necessarily random. 

Let me have a deeper look at this (likely over the weekend), and I'll get back to you.

Best Regards,
Matthew

**Comment by mballance** [comment]
Hi @pmassolino,
    I've resolved the issue that causes the 'fail to converge' issue, and different values are now produced in the low bits of the value. The distribution could be better, and I've added a pointer to issue #94 where I'm collecting information for an enhancement in this space. For now, though, release 0.5.8 should improve the situation.

Many thanks for the report and testcase!

Best Regards,
Matthew
