### ISSUE TITLE
Support for constraint with Enum type 

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#12]
Hi @mballance , I have tried to apply constraint on Enum type value. Following is the code for it:

![image](https://user-images.githubusercontent.com/29624037/86321957-a08d1a80-bc57-11ea-8c6a-674b879c073e.png)
 
and the output for this is like following : 

![image](https://user-images.githubusercontent.com/29624037/86322006-bef31600-bc57-11ea-8d9c-0f4ee6d56337.png)

As you can see in this, it is just assigning first value from given constraint. We have one usecase of this, so can you please take a look at this?

**Comment by ShraddhaDevaiya** [comment]
Hi, please let me know if any inputs are needed from my side.

**Comment by mballance** [comment]
Hi,
    This looks to be a case where you need to use 'vsc.rangelist' instead of a simple list. I've created a testcase here that shows the behavior I expect to see:
https://github.com/fvutils/pyvsc/blob/692fa2baa9cc0251411b3a8ace2854b7e65c288a/ve/unit/test_in.py#L286-L315
