### ISSUE TITLE
"not in" feature is not giving correct output in constraint !

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#13]
Hi @mballance , I have tried this **"not in"** feature with pyvsc. Following is the code  for it  : 

![image](https://user-images.githubusercontent.com/29624037/86340981-4ef28900-bc73-11ea-8408-4712ff990c87.png)

and following is the output for this code : 

![image](https://user-images.githubusercontent.com/29624037/86341069-6a5d9400-bc73-11ea-9626-7f6d4a8775f2.png)

As you can see, **self.b** value is falling in the given list range, which is not correct. So can you please check this ?

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya,
    I've investigated and, unfortunately, this is an unfortunate side-effect of how Python supports operator overloading. Python limits operator overloading to specific operators, and the boolean operators (and, or, not) are considered built-in and cannot be overloaded. 
    After investigating further, I've concluded that it's best to support dedicated methods for expressing set-membership operations. I've released a 0.0.5 version of PyVSC that provides 'inside' and 'not_inside' methods on scalar data types. Here's an example testcase using the new 'not_inside' method:
https://github.com/fvutils/pyvsc/blob/e6a0039c0b553cda90254b823d5cbef8485a2dea/ve/unit/test_in.py#L189-L210

    The new 'inside' and 'not_inside' methods should work with the same combination of operands that the overloaded 'in' operator does.

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
It is working now, thanks for your support !
