### ISSUE TITLE
Facing issue with size() function 

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#14]
Hello, I am trying to use size() function to get size of list. Following is the code for it:

![image](https://user-images.githubusercontent.com/29624037/86557245-36d08180-bf73-11ea-9ff4-5a04e4c364d8.png)

and for this , error is coming like this :

![image](https://user-images.githubusercontent.com/29624037/86557291-5a93c780-bf73-11ea-928f-216be8596455.png)

len() function is also not working for this. So, can you please help me in this?

**Comment by mballance** [comment]
Hello,
    In a constraint context, the 'size' property of a list is treated as an expression. This allows constraints to remain valid as the size of the list changes -- either because the size is random or because size of the list is programmatically changed. You need to write iterative constraints using the 'foreach' constraint. Here is an implementation of the example you show above:
https://github.com/fvutils/pyvsc/blob/b0238e780fd2fc105567c6a372f6b1033a6b664f/ve/unit/test_list_scalar.py#L100-L122
