### ISSUE TITLE
vsc.model.solve_failure.SolveFailure: solve failure

### ISSUE THREAD

**Issue by kkmonk** [fvutils/pyvsc#147]
fail find in riscv-dv tool,here is call stack
![1645264392(1)](https://user-images.githubusercontent.com/13204244/154796003-396b8473-d251-4a57-8261-23b9f05f0a2c.png)

![1645264451(1)](https://user-images.githubusercontent.com/13204244/154796041-e24a1bb8-a8cf-4351-99a7-edf40c0470ea.png)

self.illegal_instr is a @vsc.randobj ,but why it can't be solved?

**Comment by mballance** [comment]
It might be worth adding 'solve_fail_debug=1' to the call to randomize. This will trigger creation of some diagnostic info. The highlighted lines should look like the following:

```
with vsc.randomize_with(self.illegal_instr, solve_fail_debug=1):
  self.illegal_instr.exception != illegal_instr_type_e.kHintInstr
```

It's also worth reaching out to the riscv-dv project.

Can you provide instructions for reproducing this case? Specifically, information like the following will help:
- riscv-dv command and arguments used
- any special configuration data (files, options) specified
- whether the issue is always encountered, or only in some cases

-Matthew

**Comment by kkmonk** [comment]
> 
riscv-dv cmd:
`python3 run.py --simulator=pyflow --test riscv_illegal_instr_test -v`

riscv_illegal_instr_test configuration in yaml is:
- test: riscv_illegal_instr_test
  description: >
    Illegal instruction test, verify the processor can detect illegal
    instruction and handle corresponding exception properly. An exception
    handling routine is designed to resume execution after illegal
    instruction exception.
  iterations: 1
  gen_test: riscv_rand_instr_test
  gen_opts: >
    +illegal_instr_ratio=100
  rtl_test: core_base_test

and I run this cmd in a single process,here is the run function:
`riscv-dv/pygen/pygen_src/test/riscv_instr_base_test.py`
![image](https://user-images.githubusercontent.com/13204244/154871451-3daab0f5-0040-48b6-88b5-f2a5c4e69289.png)

and this issue is encountered **all the time**

**Comment by kkmonk** [comment]
i add `solve_fail_debug=1`,but it's hint seems no help for diagnose
![1645407765(1)](https://user-images.githubusercontent.com/13204244/154875552-3806f423-539f-4cd3-b5bf-52118b5e4d3e.png)

**Comment by kkmonk** [comment]
and i write a demo just like the situation ,it works well
![1645425421(1)](https://user-images.githubusercontent.com/13204244/154901781-21dc1b48-b57d-4989-bc08-617b1c02a773.png)

**Comment by aneels3** [comment]
Hi @kkmonk 
Can you specify the pyvsc version that you are using?
I am looking into the failure and it seems like non of the **PyFlow** tests are working with the latest pyvsc release (i.e 0.6.9).
I will create a separate issue to address that.
For now, you can run the tests on the older pyvsc version.
Try installing pyvsc 0.6.6.1656570787.
`pip3 install pyvsc==0.6.6.1656570787 --user`

**Comment by kkmonk** [comment]
my pyvsc version is the same as yours
![image](https://user-images.githubusercontent.com/13204244/154915137-8de46c3a-4a3e-4874-886c-6e198ff97c5a.png)
@aneels3

**Comment by aneels3** [comment]
Hi @kkmonk 
Well, on this pyvsc version the test got passed for me.
![image](https://user-images.githubusercontent.com/32580268/154916500-e39a9a4b-9bf1-4af2-8833-f932299da548.png)

My current head
![image](https://user-images.githubusercontent.com/32580268/154916649-5f0c96f1-b515-49bc-93ad-554ac02f03e6.png)

**Comment by kkmonk** [comment]
@aneels3 ,thanks for your help!
can you show me your sim.log for more detail? because if your illegal_instr_ratio set too small,it might **not enter the loop code,**and highlighted lines in my first comment  would not be executed
sim.log just like this
![image](https://user-images.githubusercontent.com/13204244/154922676-fc124f71-2ee4-4750-81f6-0925bb02fa84.png)
if bin_inst_cnt is 0, codes is not be executed
![image](https://user-images.githubusercontent.com/13204244/154796041-e24a1bb8-a8cf-4351-99a7-edf40c0470ea.png)
