### ISSUE TITLE
Passing type of object rather object in isinstance(object,type) method in to_expr(t) function in vsc.types

### ISSUE THREAD

**Issue by SkAditAziz** [fvutils/pyvsc#155]
In [types.py](https://github.com/fvutils/pyvsc/blob/master/src/vsc/types.py) at line no 329, there is a call to `isinstance()` function:
```
elif isinstance(type(t), (EnumMeta,IntEnum)):
```
`isinstance(object,type)` accept an object as the first parameter but here you are passing type of the object. Is it OK?

Again at line no 330 EnumInfo.get(e) method has been called. 
```
return expr(EnumInfo.get(type(t)).e2e(t))
```
If we see the [enum_info.py](https://github.com/fvutils/pyvsc/blob/master/src/vsc/impl/enum_info.py) file we can see it's expecting an object, not type of object.
```
@staticmethod
    def get(e)->'EnumInfo':
```
I think this is also an issue.

**Comment by mballance** [comment]
Thanks for raising the question, @SkAditAziz. Can you supply a testcase/example that exposes a problem with this code? 
The intent is to detect whether the type specified to vsc.rand_attr() is derived from an enum type. Python plays some games with enumerated types, which (if I remember correctly) is why vsc is checking for the meta-class type.

**Comment by SkAditAziz** [comment]
I was working with riscv-dv and got this issue. Now I have made a demo code portraying the problem. Please check it:

```
import vsc
import sys
from enum import Enum, IntEnum, auto

class riscv_reg_t(IntEnum):
    ZERO = 0
    RA = auto()
    SP = auto()
    GP = auto()
    TP = auto()
    T0 = auto()
    T1 = auto()
    T2 = auto()
    S0 = auto()
    S1 = auto()
    A0 = auto()
    A1 = auto()
    A2 = auto()
    A3 = auto()
    A4 = auto()
    A5 = auto()
    A6 = auto()
    A7 = auto()
    S2 = auto()
    S3 = auto()
    S4 = auto()
    S5 = auto()
    S6 = auto()
    S7 = auto()
    S8 = auto()
    S9 = auto()
    S10 = auto()
    S11 = auto()
    T3 = auto()
    T4 = auto()
    T5 = auto()
    T6 = auto()

class compressed_gpr(IntEnum):
    S0 = 8
    S1 = auto()
    A0 = auto()
    A1 = auto()
    A2 = auto()
    A3 = auto()
    A4 = auto()
    A5 = auto()

@vsc.randobj
class my_item:
    def __init__(self):
        self.loop_cnt_reg = vsc.randsz_list_t(vsc.enum_t(riscv_reg_t))
        self.loop_init_val = vsc.randsz_list_t(vsc.int32_t())

    @vsc.constraint
    def loop_c(self):
        self.loop_init_val.size.inside(vsc.rangelist(1, 2))
        with vsc.foreach(self.loop_init_val, idx = True ) as i:
            self.loop_cnt_reg[i].inside(vsc.rangelist(compressed_gpr))

obj = my_item()
obj.loop_c()
```

**Comment by mballance** [comment]
Thanks for the testcase, @SkAditAziz. I would not have expected this code to trigger a bug in the code (ie looks fine to me). I'll investigate.

**Comment by mballance** [comment]
This is an interesting case, @SkAditAziz. Thanks for sharing.
You want to constrain a set of values using an enumerated-type declaration. Now, PyVSC doesn't support directly specifying this. However, it does support specifying 'inside' on a list of values, and Python supports iterating over enumerators. Here is the last part of your testcase showing this approach:

```python3
        @vsc.randobj
        class my_item:
            def __init__(self):
                self.loop_cnt_reg = vsc.randsz_list_t(vsc.enum_t(riscv_reg_t))
                self.loop_init_val = vsc.randsz_list_t(vsc.int32_t())
        
            @vsc.constraint
            def loop_c(self):
                self.loop_init_val.size.inside(vsc.rangelist(1, 2))
                self.loop_cnt_reg.size.inside(vsc.rangelist(1, 2))
                self.loop_cnt_reg.size == self.loop_init_val.size
                with vsc.foreach(self.loop_init_val, idx = True ) as i:
                    self.loop_cnt_reg[i].inside(vsc.rangelist(list(compressed_gpr)))
        
        obj = my_item()
        obj.randomize()
```

Note that I have made two changes beyond wrapping 'compressed_gpr' with a list:
- Constrained the size of loop_cnt_reg to be the same as loop_init_val, and limited the size. PyVSC currently is a bit limited in terms of calculating the max size of lists, so a bit of extra hinting is in order.
- Added a call to 'randomize' at the end of the example

With these changes, the example runs correctly. Let me know if this approach works for you.

Thanks,
Matthew

**Comment by SkAditAziz** [comment]
@mballance Thanks for your feedback. Its working now. Wrapping 'compressed_gpr' with a list solves the issue in the riscv-dv code.
