### ISSUE TITLE
Sampling spams unhelpful messages

### ISSUE THREAD

**Issue by miserva** [fvutils/pyvsc#163]
After 0.7.6 update, whenever an object is sampled and it hits a coverpoint bin, this message is spammed:
```
# coverage_ev
# coverage_ev
# coverage_ev
# coverage_ev
```
Is this some leftover debug message? It is not particularly informative.

**Comment by mballance** [comment]
Many thanks for the report, @miserva. You're correct that this is a stray debug message that was accidentally committed. It's been cleaned up in the 0.7.8 release.
