### ISSUE TITLE
windows10 install pyboolector failed

### ISSUE THREAD

**Issue by songzenghui** [fvutils/pyvsc#165]
when i intall pyvsc, it failed because of pyboolector, so i try to install pyboolector, 
`pip install pyboolector` failed, log is 
```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\xxx\Local\Temp\pip-install-c44u7utr\pyboolector_dc3ea110fd2b400f85b0bd9f47256159\setup.py", line 14, in <module>
          with open(cmakelists_txt, "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: C:\xxx\Local\Temp\pip-install-c44u7utr\\CMakeLists.txt'
```

> os: window10
> python: 3.8
> pip: 22.2.2

pip is the newest version
@mballance 

Do I need to install [boolector](https://github.com/Boolector/boolector) in advance?

**Comment by mballance** [comment]
Ah, this is a known issue with PyBoolector. First, a binary wheel for Python requires specific compilers to be used. Boolector doesn't currently build with these compilers. Second, there is an issue installing the PyBoolector package from PyPi as a source package (ie if you've separately installed Boolector).
Are you able to compile Boolector on Windows using the instructions from Boolector? It's quite possible that you can directly use that build to satisfy the PyBoolector dependency.

**Comment by songzenghui** [comment]
THanks
Dose pyvsc support python2.7 on linux？ @mballance

**Comment by songzenghui** [comment]
I try to install `pyvsc` on linux by python2.7, but it alse failed,
log is `CMakeLists.txt not found` too.
I try to upgrade pip to newest version, but it didnt work.

**Comment by songzenghui** [comment]
please close this issue
when i update python to 3.8，it install successful
