### ISSUE TITLE
Issue with post_randomize()

### ISSUE THREAD

**Issue by aneels3** [fvutils/pyvsc#17]
It seems like the first entry in the post_randomize() method doesn't work well for all the cases.

I am trying to get the value in the post_randomize() method after each randomization call and trying to append that in post_randomize() method only like this.
![image](https://user-images.githubusercontent.com/32580268/87669422-94db4100-c78b-11ea-8a15-7c63e310255b.png)
 
Logically, If I'm calling randomize() function for 5 times then I must get 5 elements in the **self.temp** list but I am getting only four values in the list after the randomization.

![image](https://user-images.githubusercontent.com/32580268/87669621-f3082400-c78b-11ea-8ef3-c79fc9fbff8a.png)
 As you can see, I have an empty list in the post_randomize() even after appending the first random enum elements into it.

Maybe I am missing something.
Can you help me out with this issue?

**Comment by mballance** [comment]
Good catch on this issue, @aneels3! Took me a minute, but I figured out what is happening. Turns out the 'size' field within the core model for a list wasn't being updated after the append method -- only on the next randomization. Look for a fix in the 0.0.7 release, coming shortly.

**Comment by aneels3** [comment]
@mballance 
Thanks for the support.
