### ISSUE TITLE
What is the relation between pyvsc and portable stimulus (pss)?

### ISSUE THREAD

**Issue by davidmlw** [fvutils/pyvsc#180]
Can I view pyvsc an implementation of pss?

**Comment by mballance** [comment]
Hi @davidmlw,
    The short answer is "No". PyVSC provides data randomization and functional coverage collection, with similar constructs to SystemVerilog. PyVSC is a good choice if you use a Python-based simulation testbench methodology (eg cocotb, pyuvm) and want to do constrained randomization and collect functional coverage.
    PSS is a [language](https://www.accellera.org/downloads/standards/portable-stimulus) that targets modeling and generation of system-level tests -- for example, bare-metal software-driven tests for SoC-integration testing
    PSS also has data randomization and functional coverage collection, but adds on top:
    - [Actor Model-style](https://en.wikipedia.org/wiki/Actor_model) capture of scenarios that incorporate constraints over time
    - Language constructs for modeling system-level resource contention and dataflow
    - Language constructs for modeling multi-core scenarios
    - A well-defined path to create efficient software-driven tests

   I recently wrote a few blog posts as an introduction to some of the core features and capabilities of the PSS language. If you're interested, please have a read:
[Automating Bare-Metal Tests with PSS](https://bitsbytesgates.com/pss/2023/02/25/AutomatingBareMetalTestsWithPSS.html)
[PSS Fundamentals: Actions, Components, and Test Generation](https://bitsbytesgates.com/pss/2023/03/03/ActionsComponents_and_TestGeneration.html)
[Declarative Programming and Multi-Core Tests](https://bitsbytesgates.com/pss/2023/03/11/DeclarativeMultiCoreTests.html)
[Relating Actions with Dataflow](https://bitsbytesgates.com/pss/2023/03/18/RelatingActionsWithDataflow.html)
[Modeling DMA Test Scenarios with PSS](https://bitsbytesgates.com/pss/2023/03/25/ModelingTestScenariosForDMA.html)
[PSS Memory Management Fundamentals](https://bitsbytesgates.com/pss/2023/04/02/ManagingMemoryInPSS.html)
[PSS Concurrency and Resources](https://bitsbytesgates.com/pss/2023/04/09/PSSConcurrencyAndResources.html)
[Interacting with Devices via PSS Registers](https://bitsbytesgates.com/pss/2023/04/18/InteractingWithDevicesViaRegisters.html)
[Relating Actions with Dataflow Part2 -- Parallelism](https://bitsbytesgates.com/pss/2023/05/07/RelatingActionsWithDataflowPart2.html)

**Comment by davidmlw** [comment]
Many thanks. Very good blogs!

What is the status and acceptence of cocotb, pyuvm and pyvsc? I see a big opportunity for python in verification, and I think they perfectly fit the verification tasks without legacy VIP dependencies. 

What would you suggest if adopt cocotb, pyuvm and pyvsc in production?
