### ISSUE TITLE
support for function incur in constraint functions

### ISSUE THREAD

**Issue by hanfeng0114** [fvutils/pyvsc#188]
Does pyvsc support function invoking in constraint function?

**Comment by hanfeng0114** [comment]
Like the following feature:        
@vsc.constraint
            def basic_c(self):
                with vsc.foreach(self.GroupList, idx=True, it=False) as idx:
                    self.GroupList[idx]<= self.mThreadNum
                with vsc.foreach(self.GroupList, idx=True, it=False) as idx:
                    self.GroupList[idx]<= self.mThreadNum
                with vsc.foreach(self.GroupList, idx=True, it=False) as idx:
                    with vsc.if_then(self.GroupList[idx] > 1):
                        self.GroupListScore[idx] == 1
                    with vsc.else_then():
                        self.GroupListScore[idx] == 0
                self.GroupListScore.sum < self.getSum(self.GroupListScore)
                self.GroupList.sum == self.mThreadNum

            def getSum(self, aList):
                return sum(aList)

**Comment by mballance** [comment]
Can you provide a full example that includes the definition of data fields? 
Currently, PyVSC invokes functions when the constraint is built. So, getSum would be invoked once to obtain the size of the GroupListScore. Obviously, this behavior might not be what is desired.

**Comment by hanfeng0114** [comment]
For example, The following code doesn't run well for line 94:
<img width="911" alt="image" src="https://github.com/fvutils/pyvsc/assets/8148403/75e1d609-3efa-41b0-81ec-61defe618898">

Line 94 doesn't have caculation functions.
My question is how to meet similar requirement?

**Comment by mballance** [comment]
The 0.8.4 release contains changes to automatically convert floating-point number used in constraints to integers. I believe this is the best way to address this issue.
Thank you for the issue report!
