### ISSUE TITLE
Size property is not working in "for" loop

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#19]
Hello, I am trying to compute sum of list elements with **for** loop. Following is the code for it :

![image](https://user-images.githubusercontent.com/29624037/87751452-a8ce8380-c81b-11ea-98b4-f682e5494536.png)

But in this it is giving an error like following : 

![image](https://user-images.githubusercontent.com/29624037/87751512-cb609c80-c81b-11ea-9adb-5f128f2573f6.png)

As you can see, at line 15 it is working properly, but in for loop, range method it is giving an error. So can we have **sum()** function like in SV or solution to this issue , so that we can get sum of the elements of list ?

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya,
    A proper 'sum' method would be the right way to go about this. I'll look into enhancing the library to support that.

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
Hi @mballance , this issue is opened since many days. Just wanted to know, is this supported in the latest version 1.5 ?

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya,
    No, this issue is not implemented in 0.1.5. Perhaps I misunderstood the priority from your perspective. 
    From the example you supplied, it would appear that you can calculate the sum of the array elements in the 'post_randomize' method. Would this be an adequate approach for now?

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
Yeah we can do that thing, means to implement in  post_randomize method. Thanks for updating.

Regards,
Shraddha Devaiya.

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya,
    Of course. The example above, as written, has a zero-sized 'sub_program' list. I changed the example to specify the list size (10) and ensure that sub-programs are >0 in size:
```
        @vsc.randobj
        class my_s(object):
            def __init__(self):
                self.main_program = vsc.rand_uint8_t()
                self.total = vsc.rand_uint8_t()
                self.sub_program = vsc.rand_list_t(vsc.uint8_t(), sz=10)

            @vsc.constraint
            def ab_c(self):
                self.total == 50
                with vsc.foreach(self.sub_program) as it:
                    it != 0
                self.main_program + self.sub_program.sum == self.total

        my = my_s()

        # Randomize
        for i in range(5):
            my.randomize()
            print("MY ITEM : ",i+1)
            print(my.main_program , list(my.sub_program))       
```

Here is the output I see:
```
MY ITEM :  1
25 [1, 1, 1, 1, 1, 1, 1, 4, 2, 12]
MY ITEM :  2
8 [1, 1, 1, 1, 1, 1, 1, 16, 8, 11]
MY ITEM :  3
25 [1, 1, 1, 1, 1, 1, 1, 3, 3, 12]
MY ITEM :  4
0 [2, 2, 4, 2, 2, 8, 4, 2, 1, 23]
MY ITEM :  5
1 [1, 1, 1, 11, 1, 22, 2, 4, 2, 4]
```

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
Yeah, it is working, I have not provided the "size" of list that's why. Thanks for helping!

Regards,
Shraddha Devaiya.
