### ISSUE TITLE
"Created on" text in docstrings

### ISSUE THREAD

**Issue by cmarqu** [fvutils/pyvsc#2]
https://py-vsc.readthedocs.io/en/latest/reference.html#vsc.attrs.rand_attr and other places have
```
Created on Jul 23, 2019

@author: ballance
```
which looks strange.

**Comment by mballance** [comment]
Yes, I see that those are being copied into the documentation. My editor adds this tag by default when I create a file...
Is there a way to cause auto-doc to omit module-level doc comments? Failing that, I guess the module-level docstrings could converted to comments. Perhaps I shouldn't find it important, but I do like having the historical data ;-).

**Comment by cmarqu** [comment]
I'm not aware that there is a way to not include them with autodoc.
These docstrings are supposed to explain what the module contains, so the "created" metadata should be comments, I agree.

**Comment by mballance** [comment]
Okay, think I've gotten all the "Created" docstrings cleaned up and converted to comments. I'll close this for now, but do let me know if any sneaked through.
