### ISSUE TITLE
Issue with installing pyvsc library on windows 10

### ISSUE THREAD

**Issue by hodjat91** [fvutils/pyvsc#20]
Hi Matthew,

I believe that there is an issue with installing PyVSC on windows machines (mine is Windows 10). Initially I tried to install it from a virtual environment in PyCharm (tried different python/pip versions), then also tried to install it from the command line but no success. Here is the error (probably with the pyboolector library?):

```
'C:\Users\Hodja\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hodja\\AppData\\Local\\Temp\\pycharm-packaging\\pyboolector\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hodja\\AppData\\Local\\Temp\\pycharm-packaging\\pyboolector\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-pip-egg-info-c10zy0vp'
         cwd: C:\Users\Hodja\AppData\Local\Temp\pycharm-packaging\pyboolector\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hodja\AppData\Local\Temp\pycharm-packaging\pyboolector\setup.py", line 14, in <module>
        with open(cmakelists_txt, "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Hodja\\AppData\\Local\\Temp\\pycharm-packaging\\CMakeLists.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

It works for same versions of Python/Pip on various linux machines though.

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    Yes, that's an unfortunate issue with Boolector at the moment. Boolector builds for 32-bit Windows only, and only with Mingw. In order to work with PyPi, Boolector would need to build with Visual Studio tools. I've done a fair amount of work towards a native VS port, but it's incomplete at the moment. I'm also a bit concerned whether the Boolector project would wish to maintain it going forward.
    Can you explain a bit more about your use case here? Just trying to get a sense of priorities, etc...

Thanks,
Matthew

**Comment by hodjat91** [comment]
Hi Matthew,

Thanks for the quick response. It's actually not a big deal at all, and I was actually able to fix this on PyCharm on my windows machine by pointing to the python interpreter on my Linux shell through creating a WSL configuration.

Regards,
Hodjat
