### ISSUE TITLE
Set_val() and get_val() methods

### ISSUE THREAD

**Issue by hodjat91** [fvutils/pyvsc#22]
Hi Matthew,

Perhaps I'm missing something here, but I was trying to use `get/set_val` methods for a scalar attribute. Is this small piece of code valid?:

```
import vsc

x = vsc.int_t(8, 0xff)
print(x.__dir__()) # set_val() and get_val() are in the list
print("{}\n".format(x.get_val()))
```

Error: `AttributeError: 'NoneType' object has no attribute 'get_val'`

However, I can change the value of the object with `x.val` attribute.

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    Good catch, here. I didn't have any tests for using variables standalone, and they were only getting initialized when created inside a 'randobj' class. Perfectly sensible usecase, of course, so it works now (release 0.0.9). I've also added global `randomize` and `randomize_with` methods for randomizing these. Here's an example:
https://github.com/fvutils/pyvsc/blob/dab2f170ffcadb39ed670e2bc8a0887f26c855b0/ve/unit/test_field_standalone.py#L26-L33

Best Regards,
Matthew

**Comment by hodjat91** [comment]
Hi Matthew,

It seems like the `get_val()/set_val()` issue still exists for the enum type standalone variables. Say if I have `a = vsc.enum_t(my_e)`, I can't set/get value for a. 

Thanks,
Hodjat
