### ISSUE TITLE
Coverage report

### ISSUE THREAD

**Issue by hodjat91** [fvutils/pyvsc#24]
Hi Matt,

I have this small test and have a few questions regarding it:

        @vsc.covergroup
        class my_cg(object):
            def __init__(self):
                self.with_sample(dict(
                    a=vsc.uint8_t(),
                    b=vsc.uint8_t()))

                self.a_cp = vsc.coverpoint(self.a, bins=dict(
                    a_bins=vsc.bin_array([4], [0, 16])
                ))

        my_cg_1 = my_cg()
        my_cg_2 = my_cg()

        for i in range(8):
            my_cg_1.sample(i, 0)

        for i in range(16):
            my_cg_2.sample(i, 0)

        str_report = vsc.get_coverage_report(details=True)
        print("Report:\n" + str_report)

If I run this, it gives me below results:

```
Report:
TYPE my_cg : 50.000000%
    CVP a_cp : 50.000000%
    Bins:
        a_bins : 4
        a_bins : 20
        a_bins : 0
        a_bins : 0
    INST my_cg : 50.000000%
        CVP a_cp : 50.000000%
        Bins:
            a_bins : 4
            a_bins : 4
            a_bins : 0
            a_bins : 0
    INST my_cg_1 : 100.000000%
        CVP a_cp : 100.000000%
        Bins:
            a_bins : 4
            a_bins : 4
            a_bins : 4
            a_bins : 4

```

1- Results for the two instances make sense (just a minor comment, it doesn't seem to print correct names for the two instances (my_cg and my_cg1 instead of my_cg1 and my_cg2), same issue exists when multiple covergroups (TYPEs)). However, what I am concerned about is the "overall" results for the TYPE (first few lines in the above results). Especially, that "20" doesn't make sense for the second partition.

2- Say that we have multiple covergroups (each with multiple coverpoints). Is there a way to get an overall coverage report? I can see reports for individual covergroups/instances, but I'm wondering if there is a way to get the aggregated report.  

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    Good catch, here, and thanks for the test! In order to implement per-instance and per-type coverage, the first covergroup of a given type is cloned to form the type-centric covergroup. Turns out some data was being retained from the per-instance covergroup that should have been reset. I've checked in a fix, and made a new release (0.1.0). 
    With respect to covergroup-instance naming, Python isn't able to detect the name of the variable that the covergroup instance is assigned to. So, instances are named <typename>, <typename>_1, etc. It probably would make sense to provide a mechanism for the user to associate a more-meaningful instance name with the covergroup. I've opened #25 for this.

Best Regards,
Matthew

**Comment by penguali** [comment]
Hey Matt,
I stumbled upon this issue and rerun that snippet from @hodjat91 because I'm kind of in the same situation right now, where I would like instances of the same covergroup to be combined/ aggregated so that I get a total coverage combining all instances of that type. However, running the above code gives 100% coverage of the type `my_cg`. 
I expected the total coverage to be 75% here, or am I missing something here?

Here is the printed report:
```
cg.typename=my_cg
Report:
TYPE my_cg : 100.00%
    CVP a_cp : 100.00%
    Bins:
        a_bins[0] : 8
        a_bins[1] : 8
        a_bins[2] : 4
        a_bins[3] : 4
    INST my_cg : 50.00%
        CVP a_cp : 50.00%
        Bins:
            a_bins[0] : 4
            a_bins[1] : 4
            a_bins[2] : 0
            a_bins[3] : 0
    INST my_cg_1 : 100.00%
        CVP a_cp : 100.00%
        Bins:
            a_bins[0] : 4
            a_bins[1] : 4
            a_bins[2] : 4
            a_bins[3] : 4
```

Best regards,
Ali

**Comment by alwilson** [comment]
Hey @penguali,

The type coverage is going to the be the aggregate of all instance coverage, and since one of the instances has 100% coverage so will the type coverage. I think you're expecting the average instance coverage, which isn't calculated or displayed here.

Here's a similar example in the docs of two instances at 25% with no overlap, so the resulting type coverage is 50%:
https://fvutils.github.io/pyvsc/coverage.html#coverage-reports

**Comment by penguali** [comment]
Hey @alwilson,

Thanks for pointing out the example. I think I understand now how coverage for a covergroup is calculated.
Still, I think it might be useful to get an average coverage that is calculated from all instances of that group.
I'm doing this at the moment but couldn't figure out how to add the average coverage to the report, so I'm dumping it into an external text file for further processing.

Average calculation:
```
def calc_coverage_avg(report):
    """
    Takes a coverage report and iterates over all covergroups and their instances.
    Then calculate the average coverage of all instances within a covergroup.
    """
    inst_coverage = []
    req_coverage = []
    for cg in report.covergroups:
        inst_coverage = []
        for cg_inst in cg.covergroups:
            inst_coverage.append(cg_inst.coverage)
        cg.coverage = np.mean(inst_coverage)
        req_coverage.append(cg.coverage)
    report.coverage = np.mean(req_coverage)
    print(f"Requirement coverage is {report.coverage}")

    return report

```

After the test is finished, you can get the report with `report = vsc.get_coverage_report_model()` and calculate the average coverage with `avg_report = calc_coverage_avg(report)`, but then doing `vsc.report_coverage(details=True)` won't update the report with the newly calculated coverage.



PS:
Didn't expect that to work so easily, but it was worth the try :)

Best regards,
Ali
