### ISSUE TITLE
Support for weighted distribution constraint

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#26]
Hi @mballance , 
As we know in **SystemVerilog** with weighted distribution constraint, value with the more weight will get allocated more often to a random variable. We tried to implement it but couldn't find the way. We have one use case of it, so can we please have support of weighted distribution for randomization in pyvsc or some way to achieve it?

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya,
    I've implemented support for dist constraints in the 0.1.5 release. You can find examples in the tests here:
https://github.com/fvutils/pyvsc/blob/85e85de39cdf5f01095b5304368643de1db403b0/ve/unit/test_constraint_dist.py#L12-L32

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
Hi @mballance , Thanks for adding support of distribution constraint. It is working now. I have modified this code for list like following : 
```
import vsc

@vsc.randobj 
class my_c(object):
    def __init__(self): 
        self.a = vsc.rand_list_t(vsc.bit_t(7),15)
        #self.a = vsc.rand_uint8_t() 
              
    @vsc.constraint 
    def dist_a(self):
        with vsc.foreach(self.a, idx=True) as i:
            vsc.dist(self.a[i], [ 
                vsc.weight(1, 10), 
                vsc.weight(2, 20), 
                vsc.weight(4, 40), 
                vsc.weight(8, 80)])

my = my_c()

# Randomize
for i in range(3):
    my.randomize()
    print("MY ITEM : ",i+1)
    print(list(my.a))
```
and this is giving an output like following : 
```
MY ITEM :  1
[9, 6, 36, 79, 11, 108, 92, 121, 3, 70, 23, 85, 17, 0, 60]
MY ITEM :  2
[22, 96, 119, 85, 96, 77, 71, 44, 22, 74, 91, 9, 31, 117, 111]
MY ITEM :  3
[38, 28, 73, 18, 15, 98, 118, 110, 67, 15, 10, 20, 95, 58, 27]
```

I am not able understand by given in the documentation, can you please elaborate it more to understand it better?

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya,
    Thank you for the testcase. I've investigated and resolved the issue. I've both fixed the core issue with dist constraints on arrays, as well as improved the randomness of results across array elements that all have the same distribution constraint. Look for the changes in the 0.1.6 release.

Best Regards,
Matthew
