### ISSUE TITLE
Coverage report for coverpoint crosses

### ISSUE THREAD

**Issue by hodjat91** [fvutils/pyvsc#27]
Hi Matthew,

I have a couple of questions regarding this small test:

```
@vsc.covergroup
class my_cg(object):

    def __init__(self, a, b):
        super().__init__()

        self.cp1 = vsc.coverpoint(a, bins={
            "a": vsc.bin_array([], [1, 10])
        })
        self.cp2 = vsc.coverpoint(b, bins={
            "b": vsc.bin_array([], [1, 10])
        })
        self.cp1X2 = vsc.cross([self.cp1, self.cp2])


a = 6
b = 8
cg = my_cg(lambda: a, lambda: b)

for i in range(50):
    cg.sample()

vsc.report_coverage(details=True)
print("Coverage: " + str(cg.get_coverage()))
```

1- When getting the coverage report using `vsc.report_coverage(details=True)`, I can only see the coverage report (10%) for the first two coverpoints (cp1 and cp2), and not the coverpoint cross cp1X2 (I believe the coverage for cp1X2 should be 1%)

2- It seems like the result of `vsc.report_coverage(details=True)` and `cg.get_coverage()` do not match: I get 10% and 7, respectively. Is this a normal behavior?

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    I've correct this issue, and now see the expected 7% coverage associated with the covergroup and detail reports for all the cross bins. In order to get the fix, you need to update both PyVSC (0.1.2) and PyUCIS (0.0.2) packages.

Best Regards,
Matthew
