### ISSUE TITLE
Passing an object to be sampled

### ISSUE THREAD

**Issue by hodjat91** [fvutils/pyvsc#29]
Hi Matthew,

Say that I have something like this:

```
class my_e(IntEnum):
    A = auto()
    B = auto()


class my_c:
    def __init__(self):
        self.a = 5
        self.b = my_e.A


@vsc.covergroup
class my_cg(object):
    def __init__(self, input):
        super().__init__()
        self.cp1 = vsc.coverpoint(input.a,
                                  bins=dict(
                                      a=vsc.bin_array([], [1, 15])
                                  ))
        self.cp2 = vsc.coverpoint(input.b, cp_t=vsc.enum_t(my_e))


inst = my_c()
cg = my_cg(lambda: inst)
cg.sample()
vsc.report_coverage(details=True)

```
I get this error when I try to run it: 
```
self.cp1 = vsc.coverpoint(input.a,
AttributeError: 'function' object has no attribute a
```
I can actually pass all individual attributes at the instantiation time : `cg = my_cg(lambda: inst.a, lambda: inst.b)` and change the `__init__` of `my_cg` accordingly, but I was wondering if there is a possibility to pass an object as a whole at the time of instantiation. The reason that I need it is because `inst` is a `riscv_instruction` object with lots of attributes, and I want to define several `coverpoints` for each of those attributes, so it's easier to pass the whole object rather than passing too many arguments at the instantiation time. 

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    The reason for the error is that you're passing a lambda into the constructor, then trying to dereference the lamda directly to get a field. That said, currently there isn't an easy way to sample an entire object.
    Currently, most direct route would be to pass the object directly to the constructor, then use a local lambda for each coverpoint:

```
@vsc.covergroup
class my_cg(object):
    def __init__(self, input):
        super().__init__()
        self.cp1 = vsc.coverpoint(lambda: input.a,
                                  bins=dict(
                                      a=vsc.bin_array([], [1, 15])
                                  ))
        self.cp2 = vsc.coverpoint(lambda: input.b, cp_t=vsc.enum_t(my_e))


inst = my_c()
cg = my_cg(inst)
cg.sample()
vsc.report_coverage(details=True)
```

    Will an approach like this work for you? I will investigate some options involving passing vsc.rand_obj objects in parallel. Is it an option to  decorate `my_c` with vsc.rand_obj in your real application?

Thanks,
Matthew

**Comment by hodjat91** [comment]
Hi Matthew,

Thanks a lot for the explanation, it totally makes sense, and this approach is definitely fine for our need. 

Adding the capability to pass random objects with `@vsc.rand_obj` decorator would be great and will help a lot. However, it's not an essential need for our application. With that said, currently `my_c` isn't a random object in our application (It's just an object of a riscv instruction).

Thanks,
Hodjat
