### ISSUE TITLE
Partial selection & set/get_val() for enum types standalone variables

### ISSUE THREAD

**Issue by hodjat91** [fvutils/pyvsc#30]
Hi Matthew,

1- Assume that I have a standalone `a = vsc.bit_t(32, 1024)`. Is there a way to partially select and check variable a? For example, does PyVSC provide a mechanism to directly check the lower 16 bits of variable a? I know that it's provided in the constraint programming side of PyVSC, so I was curious if it's doable for standalone variables as well. Anyhow, this is not an essential needed feature as we can use the `a.get_val()` which returns an `integer` object and then manipulate it. 

2- It seems like the get_val()/set_val() issue that was fixed in #22 still exists for the enum type standalone variables (say if I have a = vsc.enum_t(my_e), I can't call set/get value for a).

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    I've added in support for part-selection on standalone variables. One unfortunate artifact of the operator overloading that generally makes accessing field values in classes easy prevents part-selection from working on members of vsc.randobj classes. Look for the new code in the 0.1.1 release -- also available now on GitHub.
    I'm not currently seeing any issues accessing the value of standalone enum variables. Please submit a testcase if you're still seeing issues.

Best Regards,
Matthew

**Comment by hodjat91** [comment]
Hi Matthew,

Thanks for adding the support for part-selection. One minor issue is that there is no boundary (width) check for a vsc type variable: if I have `a = vsc.bit_t(4, 48)`, it still assigns 48 to a (which actually should raise an error/exception saying that 48 doesn't fit in a 4-bit wide variable, I can confirm that the variable is 4-bit wide by checking the width attribute of the variable). Similarly, if I call `a.get_val(a[15])` it returns 0 while variable `a` should be 4-bit wide.

Regarding set/get_val() method for enum variables: assume this small piece of code:

```
class my_e(Enum):
    A = auto()
    B = auto()
var = vsc.enum_t(my_e)
var.set_val(my_e.A)
```
It returns `AttributeError: 'NoneType' object has no attribute 'set_val'`.

Thanks,
Hodjat

**Comment by mballance** [comment]
Hi Hodjat,
    I believe release 0.1.5 resolves these issues. Please comment back if you see more issues. You should also be able to re-open the issue.

Best Regards,
Matthew
