### ISSUE TITLE
Link to blogposts in documentation

### ISSUE THREAD

**Issue by cmarqu** [fvutils/pyvsc#4]
Your blog posts in  http://bitsbytesgates.blogspot.com/search/label/PyVSC would form a nice chapter with background info, or some parts could be a tutorial, but for now I would just add that link to the introduction.

**Comment by cmarqu** [comment]
BTW,  http://bitsbytesgates.blogspot.com/2020/03/modeling-random-stimulus-and-functional.html is not tagged "PyVSC".

**Comment by mballance** [comment]
Good suggestion, @cmarqu! I've linked the blog posts for now.
