### ISSUE TITLE
coverage issues in cocotb adder

### ISSUE THREAD

**Issue by Divyanirankari** [fvutils/pyvsc#48]
Hi, 
I have written pyvsc coverage for adder, I  have seen pyvsc documentation. but not sure about to coverage data that i am getting while running tests .
i have installed the pyucis-viewer and pyucis but not sure how to open cov.xml in pyucis-viewer.
test link: https://github.com/Divyanirankari/cocotb_tests/blob/master/pyvsc_tests/adder/tests/test_adder.py
log file:
[a.log](https://github.com/fvutils/pyvsc/files/5525039/a.log)

**Comment by mballance** [comment]
Hello @Divyanirankari,
    It might be helpful to display the values of 'a' and 'b' prior to sampling. I suspect the value of 'a' is either 0 or >15, and thus not being captured as a hit in cp1.
    To view the results in pyucis-viewer, run pyucis-viewer with cov.xml as the only argument. Let me know if you have any difficulties.

Best Regards,
Matthew

**Comment by Divyanirankari** [comment]
Hi, 

I am getting  Traceback error to view the results in pyucis-viewer.
```
$ pyucis-viewer cov.xml 
xml file
Traceback (most recent call last):
  File "/home/divya/.pyenv/versions/py36/bin/pyucis-viewer", line 8, in <module>
    sys.exit(main())
  File "/home/divya/.pyenv/versions/3.7.0/envs/py36/lib/python3.7/site-packages/pyucis_viewer/__main__.py", line 33, in main
    db = XmlFactory.read(args.file)
  File "/home/divya/.pyenv/versions/3.7.0/envs/py36/lib/python3.7/site-packages/ucis/xml/xml_factory.py", line 48, in read
    fp.seek(0)
ValueError: I/O operation on closed file.
```
and I am able to display the a and b values  and print the coverage on terminal:

```
Report:
TYPE my_covergroup : 100.000000%
    CVP cp1 : 100.000000%
    CVP cp2 : 100.000000%
    INST my_covergroup : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_1 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_2 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_3 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_4 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_5 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_6 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_7 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_8 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_9 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_10 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_11 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_12 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_13 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_14 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
    INST my_covergroup_15 : 6.250000%
        CVP cp1 : 6.250000%
        CVP cp2 : 6.250000%
```
test link: https://github.com/Divyanirankari/cocotb_tests/blob/master/pyvsc_tests/adder/tests/test_adder.py
[a.log](https://github.com/fvutils/pyvsc/files/5535684/a.log)

**Comment by mballance** [comment]
Hi @Divyanirankari,
    Thanks for catching this issue. Turns out a required data file was not being included in the pyucis package. I've updated the pyucis package, and can confirm that I'm able to use pyucis-viewer installed from PyPi. 
    You should run 'pip install pyucis --upgrade' on your Python installation in order to get the latest package. 
    I'll leave this issue open until you're able to confirm that you're able to run the viewer.

Best Regards,
Matthew

**Comment by Divyanirankari** [comment]
Thanks its working , now i am able to run pyucis-viewer

**Comment by mballance** [comment]
Appreciate the confirmation, @Divyanirankari
