### ISSUE TITLE
Not able to import vsc with the new PyPI release

### ISSUE THREAD

**Issue by aneels3** [fvutils/pyvsc#56]
Hi @mballance 
I am not able to use the pyvsc with the latest PyPI release.
Can you look into this?
![image](https://user-images.githubusercontent.com/32580268/108354313-499c7b80-720f-11eb-97e4-b2dcd71975ec.png)

**Comment by mballance** [comment]
Hi @aneels3,
     Have you tried upgrading the 'pyucis' package? I did make some additions to that package that pyvsc now depends on. Let me know if you've upgraded and are still facing difficulties.

Best Regards,
Matthew

**Comment by aneels3** [comment]
Hi @mballance 
It works after upgrading the pyucis package.
It would be really great if the user can able to installed the latest pyucis package while installing the pyvsc through PyPI.

Thanks
