### ISSUE TITLE
Getting "Attribute error:" while using "else_then" statement !

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#6]
Hello, Follwing is the code that I am running for else_then statement : 
![image](https://user-images.githubusercontent.com/29624037/84889086-e4a7e900-b0b5-11ea-97d7-07bfe7ca93d9.png)

It is giving an error like following : 
[image](https://user-images.githubusercontent.com/29624037/84888860-8e3aaa80-b0b5-11ea-8f54-a1cb6ea2a7fa.png)

Can you please help me in this and suggest some solution for this?

**Comment by mballance** [comment]
Ah... This is an interesting one. The Python error is certainly not very helpful.
The way the current library is implemented, the vsc.else_then requires parens ( vsc.else_then(): ). So, if you add parens on the vsc.else_then branch, your current code will work.

After looking at this, I'm not sure it's intuitive that else_then would require parens. So, I've updated the library to work whether or not parens are specified. Thanks for pointing this out!

**Comment by ShraddhaDevaiya** [comment]
hello, I tried this "else_then()" modification but it is giving an error like following :

![image](https://user-images.githubusercontent.com/29624037/84978635-115a1000-b14b-11ea-925e-d336338d6563.png)

So, how can I resolve this?

**Comment by ShraddhaDevaiya** [comment]
It is working. There was an issue at my end. Thanks for helping !
