### ISSUE TITLE
With list type value , it  is not randomizing with "in" feature !

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#7]
Hello, I have tried following code and in that I have used for one variable "b", constraint I have provided with **list  type** instead of **in vsc.rangelist** , but it is not randomizing the value of **b variable**:

![image](https://user-images.githubusercontent.com/29624037/85011543-4c763680-b17f-11ea-9e36-d3e586e787b8.png)

and following is the output for this code:

![image](https://user-images.githubusercontent.com/29624037/85011640-70d21300-b17f-11ea-9dd7-74f9a371711d.png)

So, can you please put some light on this?

**Comment by mballance** [comment]
Hello,
    The short answer is that PyVSC doesn't yet support the 'in <list>' constraint. The 'in' constraint currently supports vsc.rangelist on the right-hand side. 
    I've been investigating the behavior you're currently seeing, and I'm not entirely sure I understand the root cause. Basically, the 'self.b in self.temp' statement is being converted by Python into 'self.b == self.temp[0]'. 

    If supporting the 'in' constraints on lists is important to you (seems it is), please open an enhancement request to support this. 

Thanks and Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
Yes Matthew, actually we need this feature and many more which I will update you like this. So,can you please open enhancement request on this, because I don't have write access to repo, you can only do this.

**Comment by mballance** [comment]
Hi Shraddha,
    Sounds good. Please open an issue (just like this one) requesting 'in list' support. My reason for asking you to open the issue is that you'll be notified when the feature is supported.

Thanks and Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
okay. Let me do it ! Thanks for your support @mballance .

**Comment by ShraddhaDevaiya** [comment]
Hi @mballance , I tried to install pyvsc 0.0.4 with pip3, but still it is installing 0.0.3 version. So Can you please take a look at it?

**Comment by mballance** [comment]
Hi @ShraddhaDevaiya, I double-checked on this and it seems I forgot to bump the version. The version is updated, which will ensure that a new release is available on PyPi. Apologies for the delay, and hope the new release works for you!

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment]
Hello @mballance , I am able to install the **pyvsc@0.0.4**, but it is not randomizing the  value of **self.b** from the **list temp**. Same result  I am getting , which is shown below : 

![image](https://user-images.githubusercontent.com/29624037/86112253-5d129f00-bae5-11ea-974e-35f83454b72d.png)

and one more thing, we can observe here, printing of **set value**. I have not written it in code. So, any significance of this ?

**Comment by ShraddhaDevaiya** [comment]
for **set value** , I got the thing, I have used **list inside rangelist instead of tuple**, as you said new release it should be tuple. But **self.b value** is not randomizing. Can you please confirm this?
