### ISSUE TITLE
vsc.int_t initial negative values

### ISSUE THREAD

**Issue by edcote** [fvutils/pyvsc#70]
Tested with 0.3.4.20210424.1

Does not seem related to https://github.com/fvutils/pyvsc/issues/69 because the solver is not called.

```python
import random
from vsc import *

@randobj
class cl:
  def __init__(self):
    self.x = list_t(int_t(16), init=[random.randint(-2, -1) for _ in range(1)])

c = cl()
c.randomize()
if c.x[0] > 0:
  raise RuntimeError('Value greater than zero')
```

**Comment by mballance** [comment]
Hi @edcote,
    Okay, I believe this is now working properly. Fixing this issue on its own was pretty simple, but I wanted to expand the testing a bit since coverage was a bit light for width-masking on signed and unsigned types.

Fixes are present in v0.3.5 and on GitHub.

-Matthew
