### ISSUE TITLE
User control of EN_DEBUG flag

### ISSUE THREAD

**Issue by edcote** [fvutils/pyvsc#72]
RE: https://github.com/fvutils/pyvsc/discussions/65#discussioncomment-675716

This is low priority enhancement to allow user control of EN_DEBUG flag in https://github.com/fvutils/pyvsc/blob/master/src/vsc/model/randomizer.py#L60

If there's a configuration mechanism in the code I haven't seen, please point me to it and I'll implement.

Otherwise, I prefer not to rig up a mechanism unaligned with developer intent.

**Comment by mballance** [comment]
Hi @edcote,
    Good point. Having a public mechanism for controlling debug would be helpful. I'm actually thinking we might benefit from a couple levels at which debug can be set, and (possibly) a couple levels of verbosity:
- Global applied to all solves (eg vsc.debug_level(1))
- Per-solve (eg c.randomize(debug_level=1))

I think a good first step is just to expose user-level control. We can worry later about verbosity levels.
Let me give this a bit of thought. Shouldn't be difficult to implement.

**Comment by mballance** [comment]
The per-solve option has been implemented. Closing this for now. To use, pass debug=<int> to randomize call:

```
item.randomize(debug=1)
```
