### ISSUE TITLE
Random waighted distribution doesn't look random

### ISSUE THREAD

**Issue by andreyb051** [fvutils/pyvsc#75]
The goal is to get random values between 0 and 65535, but mandatory inclusion of 0 and 65535 is needed.
So: 

self.PCID = vsc.rand_uint16_t()

vsc.dist(self.PCID, [
    vsc.weight(0, 1),
    vsc.weight(vsc.rng(1,65534), 90),
    vsc.weight(65535, 1)])

Resulting values in between 1 and 65534 are not very random - a lot of 65534...
30843
65534
65534
48394
65534
65534
65534
58690
65534
59633
45598
65534
65534
37134
4344
65534
65534
0
65534
58534
65534
5014
65534
65534
65534
59632
52452
56570
65534
65534
29552
34018
65534
4222
65534
65534
53510
25660
65534
65534
58164
65534
65534
6784
65534
65534
54438
23806
9534
65534
4199
65534
65534
52208
65534
25536
24775
65534
65534
8692
13630
4564
14336
65534
13430
59902
65534
65534
41976
65534
32519
18825
65534
65534
65534
65534
18480
5256
54332
65534
65534
39422
59878
27750
65534
65534
27150
24592
61502
65534
12706
65534
64518
65534
65534
53784
57798
65534
65534
65534

**Comment by mballance** [comment]
Hmm... Yes, those results definitely seem skewed toward the high end of the 90-weight bin. 
PyVSC uses a SMT solver to do the heavy lifting of constraint solving, but the purpose of a SAT solver is to say whether an equation can be satisfied or not -- not to produce good random results. PyVSC uses the Python random package to help guide the SMT solver toward random results. In this case, at least, it appears that the random package is biasing results toward the high side of the 1..65534 domain.
I'll need to investigate this a bit more, and may take the opportunity to see if numpy would bring an improvement.

-Matthew

**Comment by andreyb051** [comment]
Thanks! If you know a better way to get a truly random distribution while hitting specific values during limited number of samplings, please tell me. I need to cover boundary conditions, but at random times.

**Comment by mballance** [comment]
Hi @andreyb051,
    This took a bit longer than I expected, but I believe the latest release of PyVSC will provide better results. I found a couple of issues with dist constraints, and the strategy for selecting a random number within valid ranges. I'm now seeing that the random-value distribution in your example is on-par with the random distribution of pure Python random. Please have a look, either by updating your PyVSC source or installing the latest PyPi package, and let me know.

Best Regards,
Matthew

**Comment by andreyb051** [comment]
Hi,

Indeed the randomization looks much better.
Is there a way to ensure hitting all ranges within a limited number of
iterations?

Thanks,
   Andrey

**Comment by mballance** [comment]
Hi @andreyb051,
    Ah, now we're getting into more interesting areas. Specifically, taking more control over the stimulus patterns that are generated. Currently, it's sort of a good news/bad news situation with PyVSC. Bad news: PyVSC doesn't specifically provide anything that helps today. Good news: Python allows us to build constraints on the fly that *should* enable fine-grained control over the stimulus generated. The key is to figure out some generally-useful patterns on how we want to control stimulus-generation patterns.

What if we had variables similar to 'randc' variables in SystemVerilog, but that allowed specifying value-range bins? This might allow you capture your stimulus-generation goals around PCID as follows:

In random order, generate:
- The value 0
- The value 65535
- A value within 90 ranges across the range 1..65534
 
Is this the type of thing you're looking for?

Best Regards,
Matthew

**Comment by andreyb051** [comment]
Hi,

My goal in this case is to generate say 20 values which are sure to have
boundary values as well as some random values.
Most values need to be random and not boundary.

Thanks
  Andrey
