### ISSUE TITLE
list type support with "in" and "not in" feature in randomization

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [fvutils/pyvsc#8]
In this we need support for "list" type value for range with "in" and "not in" feature with your tool. Currently these two things, for compilation it is working good , but it is not randomizing the value, as @mballance said in issue #7 .

**Comment by mballance** [comment]
Hi Shraddha,
    PyVSC 0.0.4 (and current top-of-trunk source) now supports randomizable and non-randomizable lists. Your example from #7 would be expressed as follows with the new features:

```
@vsc.randobj
class my_s(object):
  def __init__(self):
    self.a = vsc.rand_bit_t(8)
    self.b = vsc.rand_bit_t(8)
    self.temp = vsc.list_t(vsc.bit_t(8))

    self.temp = [1,2,3,4,5,6,7,8,9]

  @vsc.constraint
  def ab_c(self):
    self.a in vsc.rangelist(1,2, (4,8))
    self.b in self.temp
```

    Please note that intervals (eg 4..8) are now specified using a tuple (4,8).

Best Regards,
Matthew
