### ISSUE TITLE
[Low] Inheritance in constraint blocks

### ISSUE THREAD

**Issue by ShreyanJabade** [fvutils/pyvsc#91]
Hello,
The same example used in readthedocs for inheritance gives an error.

I request you to look into this aspect.
Thank you

```
@vsc.randobj
class my_base_s(object):

    def __init__(self):
        self.a = vsc.rand_bit_t(8)
        self.b = vsc.rand_bit_t(8)
        self.c = vsc.rand_bit_t(8)
        self.d = vsc.rand_bit_t(8)

    @vsc.constraint
    def ab_c(self):
       self.a < self.b

@vsc.randobj
class my_ext_s(my_base_s):

    def __init__(self):
        super().__init__()
        self.a = vsc.rand_bit_t(8)
        self.b = vsc.rand_bit_t(8)
        self.c = vsc.rand_bit_t(8)
        self.d = vsc.rand_bit_t(8)

    @vsc.constraint
    def ab_c(self):
       self.a > self.b

inst = my_ext_s()
inst.randomize()
print(inst.a)
```

Output is:

`int() argument must be a string, a bytes-like object or a number, not 'rand_bit_t'`

**Comment by mballance** [comment]
This example highlights an interesting case, since the inheriting class is re-defining fields that were previously defined by the base class. I've corrected the operator overloading logic to support re-assigning.
