### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-yghi46a5/CMakeLists.txt'

### ISSUE THREAD

**Issue by nicolast0604** [fvutils/pyvsc#96]
pip3 install --user pyvsc
Collecting pyvsc
  Using cached https://files.pythonhosted.org/packages/51/c1/bb83259df1f2376d839edeb119215b3e9f2c7f834c362d833f9f6f8cd9b6/pyvsc-0.4.7.20210703.2-py2.py3-none-any.whl
Collecting pyboolector (from pyvsc)
  Using cached https://files.pythonhosted.org/packages/9d/d2/4b244e2d3100b1d7af0e68b0181538d33d4a84e75305e296080eb74f26f2/PyBoolector-3.2.2.20210617.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yghi46a5/pyboolector/setup.py", line 14, in <module>
        with open(cmakelists_txt, "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-yghi46a5/CMakeLists.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yghi46a5/pyboolector/

**Comment by mballance** [comment]
Hi @nicolast0604,
    I actually ran into this the other day, and it's pretty counter-intuitive... PyBoolector is distributed as a binary-distribution 'wheel'. It seems that Python attempts to fallback to installation from source in some cases. The case I ran into the other day is that the version of 'pip' was incompatible with the PyBoolector package.

Can you try the following?
- Upgrade pip: pip3 install --user --upgrade pip
- Directly install PyBoolector: pip install --user --upgrade --no-cache-dir --force-reinstall --only-binary ':all:' PyBoolector

Apologies for all the switches on that last command. The goal is to force pip to ignore the cached source package for PyBoolector and install the binary one instead.

**Comment by nicolast0604** [comment]
After upgrade the pip with pip3 install --user --upgrade pip
It works for the install of pyvsc 

Thanks a lot. Appreciated for your help.
