### ISSUE TITLE
object has no attribute 'srcinfo'

### ISSUE THREAD

**Issue by aneels3** [fvutils/pyvsc#99]
Hi @mballance 
In some of the case, I am getting errors here in ctor.py
https://github.com/fvutils/pyvsc/blob/52da76b138d79a9c226f1ad25fe4fc210f1a377e/src/vsc/impl/ctor.py#L85
as 
```bash
AttributeError: 'ExprPartselectModel' object has no attribute 'srcinfo'
```

I checked your latest commit changes and tried to add the below code
```python3
self.srcinfo = None
```
in ConstraintExprModel class constructor function
https://github.com/fvutils/pyvsc/blob/52da76b138d79a9c226f1ad25fe4fc210f1a377e/src/vsc/model/constraint_expr_model.py#L30

It didn't work.
I think **e.srcinfo is None** for my case.
eventually leading to this issue.

I am attaching the SS for your reference.
![image](https://user-images.githubusercontent.com/32580268/126528569-7e930006-754b-49b8-bcc1-d56db868d297.png)

Can you help me to fix this?
Best,
Anil

**Comment by mballance** [comment]
Hi @aneels3,
    Good you caught this. The problem in this case is that the ExprPartselectModel class doesn't call the super __init__ method. If you update the constructor in expr_partselect_model.py as follows, it should work:

```
    def __init__(self, lhs, upper, lower=None):
        super().__init__() # <== Add this line
        self.lhs = lhs
        self.upper = upper 
        self.lower = lower 
```

If you want to raise a PR, I'll happily merge it in. Otherwise, I'll get a fix in later today when I get a chance.

**Comment by aneels3** [comment]
Sure
I will go ahead with the PR for this

Thanks @mballance
